'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,Sparkles,ArrowUpRight,Plus,History,Heart,MessagesSquare,Compass,Shuffle,ArrowRight,RotateCcw,Mic,Square,Keyboard,Send,Volume2,Check,ChevronLeft,Trash2,LoaderCircle,BookOpen,PanelRight, X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarInset,SidebarTrigger,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter} from '@/components/ui/alert-dialog';
import type {Attempt,Direction,Scene,Session,SessionSummary} from '@/lib/types';
import {DIRECTIONS} from '@/lib/types';
const icons={express:MessagesSquare,conflict:Compass,affection:Heart};
async function api<T>(url:string,data?:unknown,method?:string):Promise<T>{const r=await fetch(url,{method:method||(data?'POST':'GET'),...(data?{headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{})});const result=await r.json() as T & {error?:string};if(!r.ok)throw new Error(result.error||'暂未成功，请再试一次。');return result;}
const date=(s:string)=>new Date(s).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
export default function ClickApp(){
 const [configured,setConfigured]=useState<boolean|null>(null),[sessions,setSessions]=useState<SessionSummary[]>([]),[scene,setScene]=useState<Scene|null>(null),[direction,setDirection]=useState<Direction>('express'),[session,setSession]=useState<Session|null>(null),[view,setView]=useState<'start'|'practice'|'history'>('start');
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[draft,setDraft]=useState(''),[goal,setGoal]=useState(''),[goalOpen,setGoalOpen]=useState(false),[goalEditing,setGoalEditing]=useState(false),[editing,setEditing]=useState(true),[selectedAttempt,setSelectedAttempt]=useState(''),[selectedTurn,setSelectedTurn]=useState('');
 const [mode,setMode]=useState<'text'|'voice'>('text'),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[blob,setBlob]=useState<Blob|null>(null),[blobUrl,setBlobUrl]=useState(''),[audioId,setAudioId]=useState(''),[note,setNote]=useState(''),[finishOpen,setFinishOpen]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[compare,setCompare]=useState<Session|null>(null),[compareOpen,setCompareOpen]=useState(false),[archivedOpen,setArchivedOpen]=useState(false),[notice,setNotice]=useState('');
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),counter=useRef<ReturnType<typeof setInterval>|null>(null),limit=useRef<ReturnType<typeof setTimeout>|null>(null),endRef=useRef<HTMLDivElement>(null),inputRef=useRef<HTMLTextAreaElement>(null),initial=useRef(false),pendingId=useRef('');
 const current=session?.turns.at(-1); const focusTurn=session?.turns.find(t=>t.id===selectedTurn)||current;const focusAttempt=focusTurn?.attempts.find(a=>a.id===selectedAttempt)||focusTurn?.attempts.at(-1);const feedback=focusAttempt?.feedback;
 async function refresh(){const r=await api<{configured:boolean;sessions:SessionSummary[]}>('/api/bootstrap');setConfigured(r.configured);setSessions(r.sessions);return r;}
 async function work(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'暂时没有成功，请再试一次。');}finally{setBusy('');}}
 async function generate(d:Direction=direction){await work('正在准备新场景',async()=>{const s=await api<Scene>('/api/scenes',{direction:d});setScene(s);setGoal(s.goal);setDirection(d);});}
 useEffect(()=>{if(initial.current)return;initial.current=true;void (async()=>{setBusy('正在打开练习室');try{await refresh();const s=await api<Scene>('/api/scenes',{direction:'express'});setScene(s);setGoal(s.goal);}catch(e){setError(e instanceof Error?e.message:'练习室暂未打开，请刷新重试。');}finally{setBusy('');}})();},[]);
 useEffect(()=>{if(!blob){setBlobUrl('');return;}const url=URL.createObjectURL(blob);setBlobUrl(url);return()=>URL.revokeObjectURL(url);},[blob]);
 function stopRecording(){if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(counter.current)clearInterval(counter.current);if(limit.current)clearTimeout(limit.current);setRecording(false);}
 useEffect(()=>()=>{if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(counter.current)clearInterval(counter.current);if(limit.current)clearTimeout(limit.current);},[]);
 function clearDraft(){setDraft('');setBlob(null);setAudioId('');pendingId.current='';}
 async function beginRecording(){setError('');if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('当前浏览器不支持录音，可以换到支持麦克风的浏览器，或先用文字。');return;}try{const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;const mime=['audio/webm;codecs=opus','audio/mp4'].find(m=>MediaRecorder.isTypeSupported(m));const rec=new MediaRecorder(media,mime?{mimeType:mime}:undefined);const chunks:BlobPart[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=()=>{setBlob(new Blob(chunks,{type:rec.mimeType}));setAudioId('');media.getTracks().forEach(t=>t.stop());};recorder.current=rec;setBlob(null);setAudioId('');setSeconds(0);rec.start();setRecording(true);counter.current=setInterval(()=>setSeconds(s=>s+1),1000);limit.current=setTimeout(stopRecording,120000);}catch{setError('还没有获得麦克风权限。允许当前网站使用麦克风后，可以再试。');}}
 async function uploadAudio(){if(!blob)return;await work(configured?'正在转写录音':'正在保存录音',async()=>{const form=new FormData();form.set('audio',new File([blob],blob.type.includes('mp4')?'response.mp4':'response.webm',{type:blob.type}));const r=await fetch('/api/audio',{method:'POST',body:form});const result=await r.json() as {error?:string;id:string;transcript:string};if(!r.ok)throw new Error(result.error);setAudioId(result.id);if(result.transcript)setDraft(result.transcript);else setNotice('录音已保存。示例体验暂不转写，请补充文字继续体验。');});}
 async function openSession(id:string){let opened=false;await work('正在打开记录',async()=>{stopRecording();const s=await api<Session>(`/api/sessions/${id}`);setSession(s);setScene(s.scene);setGoal(s.goal);setNote(s.selfNote||'');setView('practice');setSelectedTurn('');setSelectedAttempt('');setEditing(!s.turns.at(-1)?.attempts.length);setCompare(null);clearDraft();opened=true;});return opened;}
 async function start(s:Scene=scene!,parent?:string){await work('正在开始练习',async()=>{const data=await api<Session>('/api/sessions',{sceneId:s.id,goal:parent?session!.goal:goal,parentSessionId:parent});setSession(data);setNote('');setView('practice');setGoalOpen(false);setEditing(true);setSelectedTurn('');setSelectedAttempt('');clearDraft();await refresh();});}
 async function action(kind:string,extra:Record<string,unknown>={}){if(!session)return;const s=await api<Session>(`/api/sessions/${session.id}`,{action:kind,version:session.version,...extra});setSession(s);await refresh();return s;}
 async function submit(){if(!session||!draft.trim()||recording)return;await work('正在保存回答，准备参考',async()=>{pendingId.current||=crypto.randomUUID();const s=await action('answer',{text:draft,attemptId:pendingId.current,...(mode==='voice'&&audioId?{audioId}:{})});if(s){setEditing(false);setSelectedTurn('');setSelectedAttempt(s.turns.at(-1)!.attempts.at(-1)!.id);clearDraft();}endRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'});});}
 function retry(){setEditing(true);setSelectedTurn('');clearDraft();setTimeout(()=>inputRef.current?.focus(),50);}
 async function proceed(){if(!focusAttempt)return;await work('对方正在回应',async()=>{await action('continue',{attemptId:focusAttempt.id});setEditing(true);setSelectedTurn('');setSelectedAttempt('');clearDraft();});}
 async function fork(turnId:string){await work('正在回到这个节点',async()=>{await action('fork',{turnId});setEditing(true);setSelectedTurn('');setSelectedAttempt('');clearDraft();});}
 async function finish(){await work('正在保存这次练习',async()=>{await action('finish',{note});setFinishOpen(false);});}
 function newPractice(){stopRecording();setSession(null);setView('start');setCompare(null);clearDraft();setSelectedTurn('');setSelectedAttempt('');}
 function speak(text:string){if(!('speechSynthesis'in window)){setError('当前浏览器不支持朗读。');return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';window.speechSynthesis.speak(utterance);}
 const toolsRef=useRef({generate,openSession,newPractice,session,scene});toolsRef.current={generate,openSession,newPractice,session,scene};
 useEffect(()=>{const mc=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>Promise<void>}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'click_read_practice',title:'查看当前练习',description:'读取当前可见的练习状态，不修改记录。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({scene:toolsRef.current.scene,session:toolsRef.current.session})});register({name:'click_open_practice_record',title:'打开练习记录',description:'打开已有训练记录，不提交回答或创建训练。',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const id=(input as {id?:unknown})?.id;if(typeof id!=='string'||!id||id.length>100)throw new Error('需要有效记录标识');const opened=await toolsRef.current.openSession(id);if(!opened)throw new Error('记录未能打开');return {opened,id};}});return()=>lifecycle.abort();},[]);
 const isFocusCurrent=focusTurn?.id===current?.id;const showCoach=Boolean(focusAttempt)&&(!editing||!isFocusCurrent);const statusText=busy||notice;
 return <SidebarProvider><Sidebar><SidebarHeader><div className="brand"><span className="brand-icon"><MessageCircle size={23}/></span><span>一会儿<span className="brand-en">Click</span></span></div><Button className="new-chat" onClick={newPractice} disabled={!!busy||recording}><Plus/>开启新练习</Button></SidebarHeader><SidebarContent><SidebarMenu className="px-3"><SidebarMenuItem><SidebarMenuButton onClick={()=>{stopRecording();setView('history');}} isActive={view==='history'}><History/><span>练习记录</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="side-label">最近练习</div>{sessions.length?<SidebarMenu className="px-3">{sessions.slice(0,16).map(s=><SidebarMenuItem key={s.id}><SidebarMenuButton disabled={!!busy||recording} isActive={session?.id===s.id&&view==='practice'} onClick={()=>void openSession(s.id)} className="history-link"><span className={`history-dot ${s.status==='finished'?'done':''}`}/><span className="truncate"><span>{s.title}</span><small>{date(s.updatedAt)} · {s.mode==='sample'?'示例':DIRECTIONS[s.direction].short}</small></span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>:<div className="history-empty"><History size={20}/><p>每一次开口，都留在这里。</p><span>开始练习后，随时回来看看。</span></div>}</SidebarContent><SidebarFooter><div className="profile"><span className="profile-avatar">我</span><div>我的练习室<small>给自己一点练习的空间</small></div></div></SidebarFooter></Sidebar><SidebarInset><header className="topbar"><div><SidebarTrigger/><span>{view==='history'?'练习记录':session&&view==='practice'?DIRECTIONS[session.scene.direction].label:'开始练习'}</span></div><span className="private-tag">仅自己可见</span></header>
 {configured===false&&<div className="sample-banner"><Sparkles size={15}/><span>示例体验 · OpenAI 尚未连接，当前场景、参考和对方回复均为预设示例，不用于判断进步。</span></div>}
 {error&&<div className="error-banner" role="alert"><span>{error}</span><Button variant="ghost" size="icon" aria-label="关闭错误提示" onClick={()=>setError('')}><X/></Button></div>}
 {statusText&&<div className="status-line" role="status">{busy&&<LoaderCircle className="spin" size={14}/>}<span>{statusText}</span>{!busy&&<Button size="icon-xs" variant="ghost" aria-label="关闭提示" onClick={()=>setNotice('')}><X/></Button>}</div>}
 {view==='start'&&<main className="start-main"><div className="eyebrow"><span/>来，练一会儿</div><h1>今天，想练哪一种对话？</h1><p className="intro">先说出自己的答案，再看看还有哪些可能。</p><Tabs value={direction} onValueChange={v=>void generate(v as Direction)}><TabsList className="directions">{(Object.keys(DIRECTIONS) as Direction[]).map(d=>{const Icon=icons[d];return <TabsTrigger key={d} value={d} disabled={!!busy} className="direction"><Icon/><strong>{DIRECTIONS[d].label}</strong><span>{DIRECTIONS[d].description}</span></TabsTrigger>;})}</TabsList></Tabs>
 {scene?<section className="scene-card"><div className="scene-top"><span className="scene-kicker"><Sparkles size={15}/>{scene.mode==='sample'?'场景示例':'给你的新场景'}</span><span className="scene-type">{scene.relationship}</span></div><h2>{scene.title}</h2><p className="scene-context">{scene.context}</p><div className="opening"><span>对方说</span><p>“{scene.opening}”</p></div><div className="scene-bottom"><span>{scene.challenge} · {DIRECTIONS[scene.direction].short}练习</span><div className="inline-actions"><Button variant="ghost" onClick={()=>void generate()} disabled={!!busy}><Shuffle/>换一个</Button><Button onClick={()=>{setGoal(scene.goal);setGoalEditing(false);setGoalOpen(true);}} disabled={!!busy}>进入这个场景<ArrowUpRight/></Button></div></div></section>:<section className="scene-card empty-state"><MessagesSquare/><p>{busy?'正在准备你的场景…':'场景暂未打开'}</p>{!busy&&<Button onClick={()=>void generate()}>重新打开</Button>}</section>}<p className="gentle-note">不合适就换一个。练到觉得够了，也可以随时结束。</p></main>}
 {view==='history'&&<main className="records-main"><div className="eyebrow"><span/>回头看，也是一种练习</div><h1>每一次，都是一个新起点</h1><p className="intro">回看原话与重答，也可以把同一个场景再练一次。</p>{!sessions.length?<section className="scene-card empty-state"><BookOpen/><p>这里还没有练习记录。</p><Button onClick={newPractice}>开始第一场练习<ArrowRight/></Button></section>:<div className="record-list">{sessions.map(s=><button key={s.id} className="record-card" disabled={!!busy} onClick={()=>void openSession(s.id)}><span className="record-icon">{s.mode==='sample'?<Sparkles/>:<MessageCircle/>}</span><span><strong>{s.title}</strong><small>{date(s.updatedAt)} · {s.turns} 个回答节点 · {s.mode==='sample'?'示例体验':DIRECTIONS[s.direction].short}{s.parentSessionId?' · 再次练习':''}</small></span><span className="record-status">{s.status==='finished'?'已结束':'可继续'}</span><ArrowUpRight size={17}/></button>)}</div>}</main>}
 {view==='practice'&&session&&<main className={`practice-main ${showCoach?'with-coach':''}`}><div className="conversation-column"><div className="practice-heading"><div><div className="eyebrow">{session.scene.relationship}</div><h2>{session.scene.title}</h2></div><div className="inline-actions">{session.status==='active'?<Button variant="ghost" onClick={()=>setFinishOpen(true)} disabled={!!busy||recording}>结束练习</Button>:<Button onClick={()=>void start(session.scene,session.id)} disabled={!!busy}><RotateCcw/>再练一次</Button>}</div></div><details className="context-details"><summary>情境与我的本意</summary><p>{session.scene.context}</p><p><strong>我的本意：</strong>{session.goal}</p>{session.status==='active'&&<Button variant="ghost" onClick={()=>{setGoal(session.goal);setGoalEditing(true);setGoalOpen(true);}}>调整我的本意</Button>}</details>
 <div className="conversation">{session.turns.map((turn,index)=>{const answered=turn.selectedId?turn.attempts.find(a=>a.id===turn.selectedId):turn.attempts.at(-1);return <section key={turn.id} className="turn"><div className="turn-label">第 {index+1} 轮</div><div className="opponent-row"><span className="speaker-avatar"><MessageCircle size={17}/></span><div className="opponent-bubble">{turn.opponent}<Button size="icon-sm" variant="ghost" aria-label="朗读对方的话" onClick={()=>speak(turn.opponent)}><Volume2/></Button></div></div>{answered&&<><div className="answer-meta">我 · {answered.assisted?'参考后重答':'首次回答'}{answered.mode==='voice'?' · 语音':''}</div><button className={`my-bubble ${focusTurn?.id===turn.id&&showCoach?'is-focused':''}`} onClick={()=>{setSelectedTurn(turn.id);setSelectedAttempt(answered.id);setEditing(false);}}>{answered.text}</button>{answered.audioId&&<audio className="saved-audio" controls src={`/api/audio/${answered.audioId}`} preload="none"/>}<div className="answer-tools"><Button variant="ghost" size="sm" onClick={()=>{setSelectedTurn(turn.id);setSelectedAttempt(answered.id);setEditing(false);}}><PanelRight/>查看参考{turn.attempts.length>1?` · ${turn.attempts.length} 次尝试`:''}</Button>{session.status==='active'&&turn.id!==current?.id&&<Button size="sm" variant="ghost" disabled={!!busy||recording} onClick={()=>void fork(turn.id)}><RotateCcw/>从这里重答</Button>}</div></>}</section>;})}<div ref={endRef}/></div>
 {session.status==='active'&&editing&&<section className="composer"><div className="composer-top"><span>{current?.attempts.length?'这次，换成你自己的说法':'先按你平时的方式回答'}</span><Tabs value={mode} onValueChange={v=>{if(!recording)setMode(v as 'text'|'voice');}}><TabsList><TabsTrigger value="text" disabled={recording}><Keyboard/>文字</TabsTrigger><TabsTrigger value="voice"><Mic/>语音</TabsTrigger></TabsList></Tabs></div>{mode==='voice'&&<div className="voice-area"><div className="inline-actions"><Button variant={recording?'destructive':'secondary'} disabled={!!busy} onClick={()=>recording?stopRecording():void beginRecording()}>{recording?<Square/>:<Mic/>}{recording?`结束录音 ${seconds}s`:blob?'重新录一段':'开始录音'}</Button><span className="small-muted">最长 2 分钟</span></div>{blobUrl&&<audio controls src={blobUrl}/>} {blob&&!audioId&&<Button variant="outline" disabled={!!busy||recording} onClick={()=>void uploadAudio()}>{configured?'转成文字':'保存这段录音'}</Button>}{audioId&&<span className="audio-saved"><Check size={14}/>原录音已保存，可以核对下方文字</span>}</div>}<label className="sr-only" htmlFor="answer-input">我的回答</label><Textarea ref={inputRef} id="answer-input" value={draft} maxLength={4000} onChange={e=>{setDraft(e.target.value);pendingId.current='';}} placeholder={mode==='voice'?'录音转写会出现在这里，你可以核对识别结果。':'我想说……'} disabled={!!busy||recording} className="answer-input" onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();void submit();}}}/><div className="composer-bottom"><span>提交后，才会出现参考答案。</span><div className="inline-actions">{current?.attempts.length?<Button variant="ghost" onClick={()=>setEditing(false)} disabled={!!busy}>回看上次回答</Button>:null}<Button disabled={!draft.trim()||!!busy||recording||(mode==='voice'&&Boolean(blob)&&!audioId)} onClick={()=>void submit()}><Send/>提交回答</Button></div></div></section>}
 {session.status==='active'&&!editing&&!isFocusCurrent&&<Button className="return-current" onClick={()=>{setSelectedTurn('');setSelectedAttempt('');setEditing(!current?.attempts.length);}}>回到当前节点<ArrowRight/></Button>}
 {session.status==='finished'&&<section className="session-summary"><div className="eyebrow"><Check size={15}/>这次练习，先到这里</div><p>{session.summary}</p><label htmlFor="self-note">留一句自己的感受</label><Textarea id="self-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="下次我想试试……" maxLength={2000}/><div className="inline-actions"><Button variant="secondary" disabled={!!busy} onClick={()=>void work('正在保存感受',async()=>{await action('note',{note});setNotice('感受已保存。');})}>保存感受</Button><Button variant="ghost" onClick={()=>setCompareOpen(true)}>与之前的练习对照</Button><Button variant="ghost" onClick={()=>setDeleteOpen(true)} aria-label="删除本次练习"><Trash2/></Button></div></section>}
 {session.branches.length>0&&<Button variant="ghost" onClick={()=>setArchivedOpen(true)}>查看保留的原对话分支（{session.branches.length}）</Button>}
 </div>{showCoach&&focusAttempt&&<aside className="coach-column" aria-live="polite"><div className="coach-heading"><span className="coach-icon"><Sparkles size={18}/></span><div><strong>换个方向，也可以这样说</strong><small>{session.scene.mode==='sample'?'预设参考示例':'针对你刚才的回答'}</small></div></div>{focusTurn!.attempts.length>1&&<div className="attempt-picker" aria-label="选择回答版本">{focusTurn!.attempts.map((a,i)=><Button key={a.id} variant={focusAttempt.id===a.id?'secondary':'ghost'} size="sm" onClick={()=>setSelectedAttempt(a.id)}>{i===0?'首次回答':`重答 ${i}`}</Button>)}</div>}
 {feedback?<><div className="coach-observation"><span className="small-muted">这句可能让人听成</span><p>{feedback.interpretation}</p><details><summary>为什么这样理解</summary><p>{feedback.evidence}</p><p><strong>可以保留：</strong>{feedback.keep}</p><p><strong>我的本意：</strong>{feedback.intent}</p></details></div><div className="reference-list">{feedback.references.map((r,i)=><article className="reference" key={i}><span className="reference-direction"><span>0{i+1}</span>{r.direction}</span><p>“{r.answer}”</p><details><summary>适用与取舍</summary><p>{r.tradeoff}</p></details>{isFocusCurrent&&session.status==='active'&&<Button size="sm" variant="ghost" onClick={()=>{setEditing(true);setDraft(r.answer);setMode('text');setAudioId('');pendingId.current='';setSelectedTurn('');setTimeout(()=>inputRef.current?.focus(),50);}}>放入输入框，再改改</Button>}</article>)}</div><p className="coach-practice">{feedback.practice}</p></>:<div className="coach-observation"><p>{focusAttempt.feedbackError||'回答已保存，参考尚未生成。'}</p>{isFocusCurrent&&session.status==='active'&&<Button variant="outline" disabled={!!busy} onClick={()=>void work('正在重新生成参考',async()=>{await action('feedback',{attemptId:focusAttempt.id});})}>重新生成参考</Button>}</div>}
 {isFocusCurrent&&session.status==='active'&&<div className="coach-actions"><Button className="continue-button" disabled={!!busy} onClick={()=>void proceed()}>用这句继续<ArrowRight/></Button><Button variant="outline" disabled={!!busy} onClick={retry}><RotateCcw/>这句再来一次</Button><Button variant="ghost" disabled={!!busy} onClick={()=>{setGoal(session.goal);setGoalEditing(true);setGoalOpen(true);}}>这里理解错了</Button></div>}<span className="coach-footnote">参考可以启发你，也可以不用。</span></aside>}</main>}
 <Dialog open={goalOpen} onOpenChange={setGoalOpen}><DialogContent className="goal-dialog"><DialogHeader><DialogTitle>{goalEditing?'我原本想表达的是':'这次，你想表达什么？'}</DialogTitle><DialogDescription>可以保留这个方向，也可以写下你自己的目的。</DialogDescription></DialogHeader><label htmlFor="goal">我的本意</label><Textarea id="goal" value={goal} onChange={e=>setGoal(e.target.value)} maxLength={600}/><DialogFooter><Button disabled={!goal.trim()||!!busy} onClick={()=>goalEditing?void work('正在更新本意和反馈',async()=>{await action('goal',{goal});setGoalOpen(false);}):void start()}>{goalEditing?'更新本意':'开始对话'}<ArrowRight/></Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={finishOpen} onOpenChange={setFinishOpen}><DialogContent><DialogHeader><DialogTitle>这次，练到这里</DialogTitle><DialogDescription>原话、参考和重答都会保留，之后也能再练。</DialogDescription></DialogHeader><label htmlFor="end-note">现在的感受（可不填）</label><Textarea id="end-note" value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder="有哪一句，让你有一点新发现？"/><DialogFooter><Button disabled={!!busy} onClick={()=>void finish()}>保存并结束<Check/></Button></DialogFooter></DialogContent></Dialog>
 <AlertDialog open={deleteOpen} onOpenChange={setDeleteOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>删除这次练习？</AlertDialogTitle><AlertDialogDescription>这次的对话、重答和关联录音将一并删除，无法恢复。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><Button variant="outline" onClick={()=>setDeleteOpen(false)}>保留</Button><Button variant="destructive" disabled={!!busy} onClick={()=>void work('正在删除记录',async()=>{await api(`/api/sessions/${session!.id}`,undefined,'DELETE');setDeleteOpen(false);setSession(null);setView('history');await refresh();})}>删除练习</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={compareOpen} onOpenChange={setCompareOpen}><DialogContent className="compare-dialog"><DialogHeader><DialogTitle>看看两次首次回答</DialogTitle><DialogDescription>这里只对照同一个场景；重复练习会受记忆影响，不能直接代表新情境中的能力。</DialogDescription></DialogHeader>{sessions.filter(s=>s.sceneId===session?.scene.id&&s.id!==session?.id).length?<div className="comparison-choices">{sessions.filter(s=>s.sceneId===session?.scene.id&&s.id!==session?.id).map(s=><Button key={s.id} variant={compare?.id===s.id?'secondary':'outline'} disabled={!!busy} onClick={()=>void work('正在读取对照记录',async()=>setCompare(await api<Session>(`/api/sessions/${s.id}`)))}>{date(s.updatedAt)}</Button>)}</div>:<p>还没有同场景的其他练习。可以先“再练一次”，之后回来对照。</p>}{compare&&session&&<div className="comparison-grid">{[compare,session].map(s=><section key={s.id}><span className="small-muted">{date(s.createdAt)} · {s.id===session.id?'本次':'另一次'}{s.scene.mode==='sample'?' · 示例':''}</span><p className="comparison-answer">{s.turns[0]?.attempts[0]?.text||'尚未回答'}</p><span className="small-muted">当时的本意：{s.goal}</span>{s.turns[0]?.attempts[0]?.audioId&&<audio controls preload="none" src={`/api/audio/${s.turns[0].attempts[0].audioId}`}/>}</section>)}</div>}</DialogContent></Dialog>
 <Dialog open={archivedOpen} onOpenChange={setArchivedOpen}><DialogContent className="branch-dialog"><DialogHeader><DialogTitle>保留的原对话</DialogTitle><DialogDescription>从旧节点重答时，原先的后续对话保留在这里。</DialogDescription></DialogHeader><div className="branch-content">{session?.branches.map((b,i)=><details key={i}><summary>分支 {i+1} · {date(b.createdAt)}</summary>{b.turns.map(t=><div key={t.id}><p className="small-muted">对方：{t.opponent}</p>{t.attempts.map((a,j)=><p key={a.id}>我 · {j===0?'首次':`重答 ${j}`}：{a.text}</p>)}</div>)}</details>)}</div></DialogContent></Dialog>
 </SidebarInset></SidebarProvider>;
}
