'use client';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,RotateCcw,Shuffle,Sparkles,MessageCircle,PenLine} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Input} from '@/components/ui/input';
import {DIRECTIONS,type Direction,type Exercise,type PracticeLength,type Scene,type SessionSummary} from '@/lib/types';
type Props={scene:Scene|null;direction:Direction;exercise:Exercise;length:PracticeLength;goal:string;busy:boolean;sessions:SessionSummary[];reviews:SessionSummary[];onGoal:(v:string)=>void;onLength:(v:PracticeLength)=>void;onGenerate:(d:Direction,e:Exercise,reason?:string)=>void;onStart:()=>void;onResume:(id:string)=>void;onReview:(id:string)=>void;onCustom:(data:Record<string,string>)=>void};
export default function PracticeStart(p:Props){
 const [custom,setCustom]=useState(false),[form,setForm]=useState({relationship:'',context:'',opening:'',goal:''});
 const resume=p.sessions.find(s=>s.status==='active');
 const field=(name:keyof typeof form,value:string)=>setForm({...form,[name]:value});
 return <main className="start-main"><div className="eyebrow"><span/>来，练一会儿</div><h1>一句，也算一次练习。</h1><p className="intro">先用自己的话回答，再试试另一种可能。</p>
 {resume&&<button className="resume-card" disabled={p.busy} onClick={()=>p.onResume(resume.id)}><RotateCcw size={20}/><span><strong>继续上次</strong><small>{resume.title} · {resume.turns?'接着聊':'还没回答'}</small></span><ArrowRight size={20}/></button>}
 <div className="practice-options"><div className="segmented" aria-label="练习长度">{(['quick','dialogue'] as const).map(v=><button key={v} disabled={p.busy||p.exercise==='understand'&&v==='dialogue'} aria-pressed={p.length===v} onClick={()=>p.onLength(v)}><strong>{v==='quick'?'练一句':'练一段'}</strong><small>{v==='quick'?'一个回答，随时收尾':'跟着对话继续尝试'}</small></button>)}</div><Button variant={custom?'secondary':'outline'} disabled={p.busy} onClick={()=>setCustom(!custom)}><PenLine/>{custom?'返回随机场景':'拿一件真实的事来练'}</Button></div>
 <div className="direction-pills" aria-label="训练方向">{(Object.keys(DIRECTIONS) as Direction[]).map(d=><Button key={d} variant={p.direction===d?'default':'outline'} disabled={p.busy} aria-pressed={p.direction===d} onClick={()=>p.onGenerate(d,custom?'reply':p.exercise)}>{DIRECTIONS[d].label}</Button>)}</div>
 {custom?<section className="scene-card custom-scene"><div className="scene-kicker"><PenLine size={16}/>从你的真实处境开始</div><h2>这一次，你想怎样回应？</h2><label htmlFor="real-relationship">你们是什么关系？</label><Input id="real-relationship" value={form.relationship} onChange={e=>field('relationship',e.target.value)} maxLength={100} placeholder="例如：认识多年的朋友"/><label htmlFor="real-context">刚刚发生了什么？</label><Textarea id="real-context" value={form.context} onChange={e=>field('context',e.target.value)} maxLength={1500} placeholder="写下回答需要知道的背景即可。"/><label htmlFor="real-opening">对方的原话</label><Textarea id="real-opening" value={form.opening} onChange={e=>field('opening',e.target.value)} maxLength={600} placeholder="对方说……"/><label htmlFor="real-goal">你想达到什么目的？</label><Textarea id="real-goal" value={form.goal} onChange={e=>field('goal',e.target.value)} maxLength={600} placeholder="例如：说清自己的安排，也保留以后见面的可能。"/><div className="scene-bottom"><span>按你提供的事实练习，不替对方下定论。</span><Button disabled={p.busy||Object.values(form).some(v=>!v.trim())} onClick={()=>p.onCustom(form)}>开始{p.length==='quick'?'练一句':'对话'}<ArrowUpRight/></Button></div></section>:<>
 <div className="exercise-pills" aria-label="练习玩法">{([['reply','接一句'],['repair','补救一句'],['understand','读懂一句']] as const).map(([e,label])=><button key={e} disabled={p.busy} aria-pressed={p.exercise===e} onClick={()=>p.onGenerate(p.direction,e)}>{label}</button>)}</div>
 {p.scene?<section className="scene-card"><div className="scene-top"><span className="scene-kicker"><Sparkles size={15}/>{p.scene.transferFromSessionId?'换个情境，再试一次':p.scene.mode==='sample'?'场景示例':'这次的场景'}</span><span className="scene-type">{p.scene.relationship}</span></div><h2>{p.scene.title}</h2><p className="scene-context">{p.scene.context}</p><div className="opening"><span>对方说</span><p>“{p.scene.opening}”</p></div>{p.scene.exercise==='understand'&&<p className="exercise-task">哪些是确定知道的，哪些只是你的猜测？你会怎样确认？</p>}<label htmlFor="start-goal" className="inline-goal-label">这次的本意 <span>可以直接改成自己的目的</span></label><Textarea id="start-goal" value={p.goal} onChange={e=>p.onGoal(e.target.value)} maxLength={600} className="inline-goal"/><div className="scene-bottom"><span>{p.scene.skill}</span><div className="inline-actions"><Button variant="ghost" onClick={()=>p.onGenerate(p.direction,p.exercise)} disabled={p.busy}><Shuffle/>换一个</Button><Button onClick={p.onStart} disabled={p.busy||!p.goal.trim()}>开始{p.length==='quick'?'练一句':'对话'}<ArrowUpRight/></Button></div></div><details className="skip-reasons"><summary>这题不太适合我</summary><div>{['太容易了','不像我的生活','今天不想练这个'].map(reason=><Button key={reason} size="sm" variant="ghost" disabled={p.busy} onClick={()=>p.onGenerate(p.direction,p.exercise,reason)}>{reason}</Button>)}</div><small>选一下就换题，只调整近期推荐。</small></details></section>:<section className="scene-card empty-state"><MessageCircle/><p>{p.busy?'正在准备你的场景…':'选一个方向，从一句话开始。'}</p><Button disabled={p.busy} onClick={()=>p.onGenerate(p.direction,p.exercise)}>准备一个场景<ArrowRight/></Button></section>}</>}
 {p.reviews.length>0&&<section className="review-suggestions"><span className="small-muted">隔了几天，可以换个情境再试试</span>{p.reviews.map(r=><button key={r.id} disabled={p.busy} onClick={()=>p.onReview(r.id)}><span><strong>{r.nextFocus||r.skill}</strong><small>上次：{r.title}</small></span><ArrowRight size={18}/></button>)}</section>}
 <p className="gentle-note">参考始终在回答后出现。练到够了，就可以停。</p></main>;
}
