import type {Scene,Direction,Feedback} from './types';
const samples:Omit<Scene,'id'|'mode'|'direction'>[][]=[
[{title:'想帮忙，却像在否定对方',relationship:'熟悉的同事 · 当面',context:'同事试了几次都没完成一个操作，来问你。你恰好做过这件事，想帮忙，也不希望自己的熟练让对方感到被轻视。',opening:'这个怎么弄啊，我试了好几次都不行。',goal:'让对方知道我会做，也愿意帮忙。',skill:'表达本意 · 具体询问',challenge:'日常'},{title:'一句“随便”，让安排卡住了',relationship:'朋友 · 私聊',context:'朋友在替你们选聚餐地点。你此前说“随便”，其实只是不想给对方添麻烦，但确实有不喜欢的食物。朋友发来一家你不太想去的店。',opening:'那就这家吧？你刚刚不是说都可以吗？',goal:'说清自己的偏好，并一起找到可行选择。',skill:'澄清含糊表达',challenge:'有一点变化'},{title:'你想提建议，对方听成了否定',relationship:'合作伙伴 · 工作私聊',context:'对方刚分享一个投入很多精力的方案。你认可整体方向，但发现一个具体环节可以更清楚。对方听到你说“还可以改”后停了一下。',opening:'所以你觉得我这个方案不行？',goal:'区分对整体的认可和对具体环节的建议。',skill:'具体表达 · 修复误会',challenge:'需要澄清'}],
[{title:'约好的周末，又被临时取消',relationship:'朋友 · 私聊',context:'你和一位熟悉的朋友约好周末见面。这已经是对方第二次临时改约。你还想见面，也想让对方知道，临时变动会影响你的安排。',opening:'这周有点累，改天吧。',goal:'说清临时变动的影响，并确认下一步安排。',skill:'表达影响 · 确认下一步',challenge:'需要立场'},{title:'“顺手帮一下”，已经占了一个晚上',relationship:'同事 · 下班后消息',context:'同事之前请你临时帮忙，你已经花了一个晚上。今天他又发来新的任务。你有自己的安排，愿意提供一点信息，但不想继续接手。',opening:'你上次做得挺快的，这次也顺手帮我弄一下呗。',goal:'拒绝继续接手，说清自己愿意提供的有限帮助。',skill:'明确边界',challenge:'需要立场'},{title:'你的在意，被一句话带过',relationship:'亲近的人 · 当面',context:'你刚说起一件让你不舒服的小事，对方觉得事情不大。你希望对方理解这件事对你的影响，但也不想把话题越说越远。',opening:'就这么点事，你至于吗？',goal:'说清为什么在意，以及希望对方怎样回应。',skill:'表达不满与需要',challenge:'需要停一下'}],
[{title:'“你是不是对谁都这么好？”',relationship:'有好感的人 · 私聊',context:'你记得对方上次随口提到的喜好，今天顺手发了一个相关分享。你们已经聊过几次，能轻松开玩笑，但还没有明确说过好感。',opening:'你是不是对谁都这么好？',goal:'自然回应，尝试表达一点特别的关注。',skill:'接住试探 · 表达好感',challenge:'轻松互动'},{title:'想约见面，对方没有给准话',relationship:'刚熟悉的人 · 私聊',context:'你们最近聊得不错，你想约对方周末看一个展。你已经提出邀约，对方没有明确答应或拒绝。你希望问清楚，也想留出对方选择的空间。',opening:'听起来还不错诶，不过周末可能有点事。',goal:'轻松确认意愿，不勉强对方。',skill:'确认意愿 · 留有余地',challenge:'信息含糊'},{title:'收到夸奖，一时不知道怎么接',relationship:'有好感的人 · 见面后消息',context:'你们刚参加完一次朋友聚会。对方主动发来消息，夸你刚才讲的一段故事。你很开心，想接住赞美并把聊天继续下去。',opening:'你刚才讲那段太有意思了，感觉你挺有趣的。',goal:'自然接受夸奖，并回应对对方的兴趣。',skill:'接受夸奖 · 继续互动',challenge:'轻松互动'}]
];
export function sampleScene(direction:Direction,index:number):Scene { const group=direction==='express'?0:direction==='conflict'?1:2;return {...samples[group][index%samples[group].length],id:crypto.randomUUID(),direction,mode:'sample',sampleIndex:index}; }
export function sampleFeedback(scene:Scene):Feedback {let references=scene.direction==='affection'?[{direction:'真诚直接',answer:'我对你确实会多留意一点。',tradeoff:'适合愿意更明确表达兴趣的时候。'},{direction:'轻轻逗趣',answer:'你这是在确认自己是不是特别待遇吗？',tradeoff:'适合双方已经能开玩笑的关系。'},{direction:'先问清楚',answer:'你是开玩笑，还是认真想知道呀？',tradeoff:'先澄清，会稍微放慢互动节奏。'}]:scene.direction==='conflict'?[{direction:'说清影响',answer:'我理解你累了，不过临时改约也会影响我的安排。',tradeoff:'先说明自己的处境，让对方知道你为什么在意。'},{direction:'确认下一步',answer:'那你想改到哪天？如果还没确定，我们先各自安排。',tradeoff:'将含糊的“改天”变成可以讨论的下一步。'},{direction:'表达边界',answer:'这次就先取消吧。下次如果需要改时间，希望能提前告诉我。',tradeoff:'保留边界，也让这次对话可以收尾。'}]:[{direction:'表达本意',answer:'这个我之前做过，要不要一起看看？',tradeoff:'直接让对方知道愿意提供帮助。'},{direction:'具体询问',answer:'你现在卡在哪一步？',tradeoff:'先了解对方遇到的具体问题。'},{direction:'补充澄清',answer:'我想说的是我比较熟，可以帮你看看。',tradeoff:'适合已经意识到自己刚才说得不够清楚时。'}];
const variants:Record<string, {direction:string;answer:string;tradeoff:string}[]>={
express1:[{direction:'说清偏好',answer:'我刚才说得太笼统了。我都能商量，但这家我不太想吃。',tradeoff:'承认原话含糊，也说明真实偏好。'},{direction:'给个可行选择',answer:'要不看看另一家？我来找两家我们都能吃的。',tradeoff:'自己承担一点选择工作，让对话有下一步。'},{direction:'补充限制',answer:'我没有特别想吃的，不过今天想避开这类菜，可以吗？',tradeoff:'区分没有强偏好和完全没有限制。'}],
express2:[{direction:'区分整体与细节',answer:'我认可整体方向，想讨论的是其中一个环节。',tradeoff:'先纠正“整体不行”的误会。'},{direction:'先问是否方便',answer:'不是否定你。我有个具体想法，你现在方便一起看看吗？',tradeoff:'说明本意，也给对方选择讨论时机的空间。'},{direction:'修复刚才的说法',answer:'刚才“还可以改”说得太笼统了，让我重新说清楚。',tradeoff:'先修复含糊表达，再具体指出所指环节。'}],
conflict1:[{direction:'直接表达边界',answer:'这次我有自己的安排，没办法继续接手了。',tradeoff:'清楚拒绝，不把拒绝藏在含糊的推辞里。'},{direction:'提供有限帮助',answer:'我不能帮你做完，不过可以把上次的方法发给你。',tradeoff:'说明愿意提供的帮助及其范围。'},{direction:'纠正顺手的预期',answer:'上次其实花了我一个晚上，这次需要你自己安排了。',tradeoff:'让对方了解真实投入，但不需要说服对方认可你才能拒绝。'}],
conflict2:[{direction:'说出具体影响',answer:'对你可能是小事，但这件事确实让我不舒服，我想说清楚原因。',tradeoff:'说明自己的感受，不争论是否“至于”。'},{direction:'表达需要',answer:'我想先把话说完，也希望你先听听我为什么在意。',tradeoff:'让对方知道此刻需要怎样的回应。'},{direction:'暂时停一下',answer:'我们现在好像没听懂彼此，先停一会儿，之后再说吧。',tradeoff:'适合当下难以继续交流，之后仍需决定是否重启话题。'}],
affection1:[{direction:'给出轻松选择',answer:'没关系，你看周六还是周日方便？都不合适就下次。',tradeoff:'提供具体选择，同时保留婉拒空间。'},{direction:'先确认兴趣',answer:'你对这个展有兴趣吗？有的话，我们再找合适的时间。',tradeoff:'先区分时间不合适和对活动兴趣不大。'},{direction:'留白收尾',answer:'好呀，那先不急着定。你有空、也想去的话再告诉我。',tradeoff:'把下一步留给对方，也接受对方可能不会继续邀约。'}],
affection2:[{direction:'自然接住夸奖',answer:'谢谢，听你这么说我还挺开心的。',tradeoff:'不急着自我否定，先接受对方的赞美。'},{direction:'轻轻逗趣',answer:'看来今天我的故事库存没白准备。下次换你讲一个？',tradeoff:'适合轻松氛围，给下一次互动一个接点。'},{direction:'回应自己的兴趣',answer:'我也挺喜欢听你聊的，刚才还觉得没聊够。',tradeoff:'适合你确实有这种感受时，让兴趣更明确一点。'}]
};references=variants[scene.direction+String((scene.sampleIndex||0)%3)]||references;
return {intent:scene.goal,interpretation:'此处将展示对方可能如何理解你的具体回答。',evidence:'这是预设的界面示例，没有分析你的回答。',keep:'真实反馈会引用你实际说过的内容。',practice:'先体验“回答—看参考—重答或继续”的节奏。',references};}
